# Generated by Django 3.1.7 on 2021-12-25 22:17

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarryOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('indexed_date', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('indexed_date', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('indexed_date', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=30)),
                ('is_dealer', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('type_of_request', models.CharField(max_length=30)),
                ('route_of_request', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('result', models.CharField(max_length=10)),
                ('msg_id', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('numbers', models.CharField(max_length=10)),
                ('points_charged', models.CharField(max_length=10)),
                ('balance_after', models.CharField(max_length=10)),
                ('UNIX_timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('indexed_date', models.IntegerField(db_index=True)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='offers/')),
                ('price', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField()),
                ('date_fullfilled', models.DateTimeField(auto_now_add=True)),
                ('indexed_date', models.IntegerField()),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=1)),
                ('redirect_destination', models.CharField(default='home', max_length=1000)),
                ('date_fullfilled', models.DateTimeField(blank=True, null=True)),
                ('indexed_date', models.IntegerField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction', to='administration.offer')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='administration.purchase')),
            ],
        ),
    ]
