# Generated by Django 3.1.7 on 2021-12-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('public', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_purchases', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='message',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='deleteddeal',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_deals', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='deleteddeal',
            name='property_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.propertyarea'),
        ),
        migrations.AddField(
            model_name='deleteddeal',
            name='property_outlook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.propertyoutlook'),
        ),
        migrations.AddField(
            model_name='deleteddeal',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.propertytype'),
        ),
        migrations.AddField(
            model_name='deallog',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='public.deal'),
        ),
        migrations.AddField(
            model_name='deallog',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='deallog',
            name='deleted_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='logs', to='administration.deleteddeal'),
        ),
        migrations.AddField(
            model_name='credit',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='carryover',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_over', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='dealer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='administration.role'),
        ),
        migrations.AddIndex(
            model_name='carryover',
            index=models.Index(fields=['dealer', 'indexed_date'], name='administrat_dealer__46f9f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carryover',
            unique_together={('dealer', 'indexed_date')},
        ),
    ]
