# Generated by Django 3.1.7 on 2021-12-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('phone', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
