# Generated by Django 3.1.7 on 2021-12-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='office.office'),
        ),
    ]
